global:
  resolve_timeout: 1m

route:
  receiver: 'slack'
  group_by: ['alertname', 'service']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1h

receivers:
  - name: 'slack'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/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'
        channel: '#observability'
        send_resolved: true
        text: |
          {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}
